#!/bin/bash
composer require laravel-frontend-presets/tailwindcss

#php artisan preset tailwindcss
php artisan preset tailwindcss-auth

npm install && npm run dev && npm run dev

sed -i -e "s/purgeCss()/purgeCss()\n\t\.browserSync(\'${PWD##*/}\.test\')/g" webpack.mix.js

