#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

sudo rm -rf $1

#/etc/hosts
sudo sed -i "/${1}.test/d" /etc/hosts
sudo rm /etc/nginx/sites-available/$1
sudo rm /etc/nginx/sites-enabled/$1
sudo rm /var/www/$1
sudo nginx -t

DIR=${1//[^a-zA-Z0-9]/_}

mysql -uroot -proot -e "DROP DATABASE ${DIR};"

