#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

DIR=${1//[^a-zA-Z0-9]/-}

#/etc/hosts
sudo bash -c "cp /etc/hosts /etc/hosts.original"
sudo bash -c "echo -e '127.0.0.1\t$DIR.test' >> /etc/hosts"

#server-block
sudo cp /etc/nginx/sites-available/server-block-template /etc/nginx/sites-available/$DIR
sudo sed -i -e "s/template/${DIR}/g" /etc/nginx/sites-available/$DIR
sudo ln -s /etc/nginx/sites-available/$DIR /etc/nginx/sites-enabled/
sudo nginx -t
sudo service nginx restart
sudo ln -s ~/code/$DIR /var/www

git clone https://github.com/spatie/blender.git ${DIR}

cd ${DIR}

cp .env.example .env

sed -i -e "s/nl/en/g" config/app.php
sed -i -e "s/'en', 'en'/'en'/g" config/app.php
sed -i -e "s/blender/${DIR}/g" .env
sed -i -e "s/\})\;/\})\n\t.browserSync(\'${DIR}\.test\');/" webpack.mix.js
sed -i -e 's/<\/php>/\t<env name=\"DB_DATABASE\" value=\":memory:\"\/>\n\t<\/php>/' phpunit.xml
sed -i "/maatwebsite/d" composer.json
sed -i -e "s/date(string \$name = '', ?string/date(\$name = \'\', /" app/Services/Html/Concerns/Forms.php
sed -i -e "s/localhost/127\.0\.0\.1/" .env

code .

composer update

DB=${DIR//[^a-zA-Z0-9]/_}

mysql -uroot -proot -e "CREATE DATABASE ${DB} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

sed -i "/DB_DATABASE=${DIR}/c\DB_DATABASE=${DB}" .env
sed -i "/DB_PASSWORD=/c\DB_PASSWORD=root" .env

composer require --dev beyondcode/laravel-dump-server

php artisan migrate --seed

php artisan key:generate

npm install

npm run dev && npm run dev

rm -rf .git

git init

sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache

# Download Laravel/tests from github
git clone https://github.com/laravel/laravel.git
rm -rf tests/Concerns
rm -rf tests/Features
rm -rf tests/Unit
cp laravel/tests/* tests
rm -rf laravel
