#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

DIR=${1//[^a-zA-Z0-9]/-}

laravel new $1

cd $DIR

code .

sed -i -e 's/<\/php>/\t<env name=\"DB_CONNECTION\" value=\"sqlite\"\/>\n\t\t<env name=\"DB_DATABASE\" value=\":memory:\"\/>\n\t<\/php>/g' phpunit.xml

DIR=${DIR//[^a-zA-Z0-9]/_}

mysql -uroot -proot -e "CREATE DATABASE ${DIR} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

sed -i "/DB_DATABASE=homestead/c\DB_DATABASE=${DIR}" .env
sed -i "/DB_USERNAME=homestead/c\DB_USERNAME=root" .env
sed -i "/DB_PASSWORD=secret/c\DB_PASSWORD=root" .env

composer require --dev beyondcode/laravel-dump-server

php artisan make:auth

cp -f /home/y/code/linux-mint-setting/Laravel/stubs/DatabaseSeeder.php database/seeds/
cp -f /home/y/code/linux-mint-setting/Laravel/stubs/helpers.php bootstrap/
cp -f /home/y/code/linux-mint-setting/Laravel/stubs/index.php public
cp -f /home/y/code/linux-mint-setting/Laravel/stubs/TestCase.php tests

php artisan migrate

git init

git add .

git commit -m 'initial'
