#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

DIR=${1//[^a-zA-Z0-9]/-}

git clone https://github.com/pkboom/blender.git ${DIR}

cd ${DIR}

cp .env.example .env

sed -i -e "s/blender/${DIR}/g" .env
sed -i -e "s/blender/${DIR}/g" webpack.mix.js

code .

composer update

DB=${DIR//[^a-zA-Z0-9]/_}

mysql -uroot -proot -e "CREATE DATABASE ${DB} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

sed -i -e "s/DB_DATABASE=${DIR}/DB_DATABASE=${DB}" .env

composer require --dev beyondcode/laravel-dump-server

php artisan key:generate

npm install

npm run dev && npm run dev

php artisan migrate --seed

git init

git add .

git commit -m 'initial'

#sudo chgrp -R www-data storage bootstrap/cache
#sudo chmod -R ug+rwx storage bootstrap/cache

