#!/bin/bash
if [ $# -eq 0  ] #  no argument present
then
    echo "No arguments provided"
    exit 1
fi

DIR=${1//[^a-zA-Z0-9]/-}

laravel new $1

cd $DIR

code .

sed -i -e '/APP_ENV=/ s/=.*/=&\n\t\t<env name=\"DB_CONNECTION\" value=\"sqlite\"\/>\n\t\t<env name=\"DB_DATABASE\" value=\":memory:\"\/>/' phpunit.xml

DIR=${DIR//[^a-zA-Z0-9]/_}

mysql -uroot -pa -e "CREATE DATABASE IF NOT EXISTS $DIR CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"

# Only if line contains baz, substitute foo with bar
# sed '/baz/s/foo/bar/g' file.txt
sed -i -e "/DB_DATABASE=/ s/=.*/=$DIR/" .env
sed -i -e "/DB_USERNAME=/ s/=.*/=root/" .env
sed -i -e "/DB_PASSWORD=/ s/=.*/=a/" .env

# php artisan make:auth

cp -f /home/y/linux-setup/laravel/stubs/DatabaseSeeder.php database/seeds/
cp -f /home/y/linux-setup/laravel/stubs/helpers.php bootstrap/
cp -f /home/y/linux-setup/laravel/stubs/TestCase.php tests

php artisan migrate

git init

git add .

git commit -m 'initial'
