#!/bin/bash

read -p "Are you in the project? (n/y) " -n 1 -r

echo

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    read -p "Folder name ($package_name): " folder_name

    dir=${folder_name//[^a-zA-Z0-9]/-}

    cd $dir
fi

echo

composer require laravel-frontend-presets/tailwindcss

php artisan preset tailwindcss
#php artisan preset tailwindcss-auth

npm install && npm run dev && npm run dev
npm install && npm run dev && npm run dev

sed -i -e "s/purgeCss()/purgeCss()\n\t\.browserSync(\'${PWD##*/}\.test\')/g" webpack.mix.js

rm tailwind.js
npx tailwind init tailwind.js

