#!/bin/bash
if [ $# -eq 0  ] #  no argument present
then
    echo "No project name provided"
    exit 1
fi

dir=${1//[^a-zA-Z0-9]/-}

laravel new $1

cd $dir

code .

sed -i -e '/APP_ENV/ s/APP_ENV.*/&\n\t\t<env name=\"DB_CONNECTION\" value=\"sqlite\"\/>\n\t\t<env name=\"DB_DATABASE\" value=\":memory:\"\/>\n\t\t<env name=\"TELESCOPE_ENABLED\" value=\"false\"\/>/' phpunit.xml

dir=${dir//[^a-zA-Z0-9]/_}

mysql -u root -pa -e "CREATE DATABASE IF NOT EXISTS $dir CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"

# Only if line contains baz, substitute foo with bar
# sed '/baz/s/foo/bar/g' file.txt
sed -i -e "/DB_DATABASE=/ s/=.*/=$dir/" .env
sed -i -e "/DB_USERNAME=/ s/=.*/=root/" .env
sed -i -e "/DB_PASSWORD=/ s/=.*/=a/" .env

# php artisan make:auth
stub="$HOME/.dotfiles/scripts/stubs"
cp -f $stub/DatabaseSeeder.php database/seeds/
#cp -f $current/helpers.php bootstrap/
cp -f $stub/.idea .

php artisan migrate:fresh --seed

git init

git add .

git commit -m 'initial'

npm install
