#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

laravel new $1

DIR=${1//[^a-zA-Z0-9]/-}

#/etc/hosts
sudo bash -c "cp /etc/hosts /etc/hosts.original"
sudo bash -c "echo -e '127.0.0.1\t$DIR.test' >> /etc/hosts"

#httpd-vhosts.conf
VHOSTSFILE="/opt/lampp/etc/extra/httpd-vhosts.conf"
sudo bash -c "cp ${VHOSTSFILE} ${VHOSTSFILE}.original"
sudo bash -c "echo '<VirtualHost *:80> #${DIR}' >> $VHOSTSFILE"
sudo bash -c "echo -e '\tDocumentRoot ${PWD}/${DIR}/public' >> $VHOSTSFILE"
sudo bash -c "echo -e '\tServerName ${DIR}.test' >> $VHOSTSFILE"
sudo bash -c "echo '</VirtualHost> #${DIR}' >> $VHOSTSFILE"

cd $1

code .

sudo chmod -R 777 storage

sed -i -e 's/<\/php>/\t<env name=\"DB_CONNECTION\" value=\"sqlite\"\/>\n\t\t<env name=\"DB_DATABASE\" value=\":memory:\"\/>\n\t<\/php>/g' phpunit.xml

DIR=${DIR//[^a-zA-Z0-9]/_}

mysql -uroot -proot -e "CREATE DATABASE ${DIR} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

sed -i "/DB_DATABASE=homestead/c\DB_DATABASE=${DIR}" .env
sed -i "/DB_USERNAME=homestead/c\DB_USERNAME=root" .env
sed -i "/DB_PASSWORD=secret/c\DB_PASSWORD=root" .env

composer require --dev beyondcode/laravel-dump-server

sudo /opt/lampp/lampp restart
